<?php

namespace Database\Seeders;

use App\Models\CalculatorItem;
use Illuminate\Database\Seeder;

class CalculatorItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $spa_items = [
            [
                'cid' => 1,
                'section' => 'professional_charges',
                'type_of_price' => 'property_legal_fee',
                'name' => 'sale_purchase_fees',
                'label' => 'Sale and Purchase Agreement',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'entry_withdrawal_caveat',
                'label' => 'Entry & Withdrawal of Private Caveat',
                'price' => 350.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'statutory_declaration',
                'label' => 'Statutory Declaration',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'filling_form_I',
                'label' => 'Filing Form I',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'professional_charges',
                'type_of_price' => 'pax',
                'name' => 'ckht_2a',
                'label' => 'CKHT 2A',
                'price' => 300,
                'subsequent_price' => 200,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'affirmation_sd_fee',
                'label' => 'Affirmation Fee for Statutory Declaration',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'travelling_despatch',
                'label' => 'Travelling & Despatch',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'courier_postage',
                'label' => 'Courier & Postage',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'printing_stationery',
                'label' => 'Printing and Stationery',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'misc',
                'label' => 'Miscellaneous',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'memo_of_transfer',
                'name' => 'transfer_memo_stamp_duty',
                'label' => 'Stamp Duty of Memorandum of Transfer',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'memo_of_transfer',
                'name' => 'transfer_memo_fee',
                'label' => 'Registration Fees for Memorandum of Transfer',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'reg_entry_private_caveat_fee',
                'label' => 'Registration Fees for Entry of Private Caveat',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'reg_withdrawal_private_caveat_fee',
                'label' => 'Registration Fees for Withdrawal of Private Caveat',
                'price' => 60.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_spa',
                'label' => 'Stamp Duty of Sale and Purchase Agreement',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_statutory_declaration',
                'label' => 'Stamp Duty of Statutory Declaration',
                'price' => 10.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'property_legal_fee',
                'name' => 'other_fees',
                'label' => 'Bankruptcy / Winding-up Search',
                'price' => null,
                'subsequent_price' => 30,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'land_search',
                'label' => 'Land Search',
                'price' => 180.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 1,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'form_I',
                'label' => 'Form I',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        $loan_items = [
            [
                'cid' => 2,
                'section' => 'professional_charges',
                'type_of_price' => 'property_legal_fee',
                'name' => 'facility_agreement',
                'label' => 'Facility Agreement',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'professional_charges',
                'type_of_price' => 'min_pp',
                'name' => 'memo_charge',
                'label' => 'Memorandum of Charge',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => 10,
                'min_price' => 300,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'entry_withdrawal_caveat',
                'label' => 'Entry & Withdrawal of Caveat',
                'price' => 350.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'statutory_declaration',
                'label' => 'Statutory Declaration',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'affirmation_sd_fee',
                'label' => 'Affirmation Fee for Statutory Declaration',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'travelling_despatch',
                'label' => 'Travelling & Despatch',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'courier_postage',
                'label' => 'Courier & Postage',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'printing_stationery',
                'label' => 'Printing and Stationery',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'misc',
                'label' => 'Miscellaneous',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'purchase_document_fees',
                'label' => 'Purchase Document Fees',
                'price' => 350.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'property_legal_fee',
                'name' => 'stamp_duty_facility_agreement',
                'label' => 'Stamp Duty of Facility Agreement (FA)',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_dfa',
                'label' => 'Stamp Duty on Duplicate FA - 2 copies',
                'price' => 20.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_letter_offer',
                'label' => 'Stamp Duty on Letter of Offer',
                'price' => 30.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_charge_annexures',
                'label' => 'Stamp Duty on Charge & Annexures',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sup_letter_offer',
                'label' => 'Supplementary Letter of Offer',
                'price' => 0.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_statutory_declaration',
                'label' => 'Stamp Duty on Statutory Declaration',
                'price' => 20.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'land_search',
                'label' => 'Land Search / Officeal Land Search',
                'price' => 240.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'reg_charge',
                'label' => 'Registration of Charge',
                'price' => 120.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'reg_entry_withdrawal',
                'label' => 'Registration of Entry and Withdrawal/Caveator\'s Consent',
                'price' => 210.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 2,
                'section' => 'disbursements',
                'type_of_price' => 'property_legal_fee',
                'name' => 'other_fees',
                'label' => 'Bankruptcy / Winding-up Search',
                'price' => null,
                'subsequent_price' => 30,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        $master_loan_items = [
            [
                'cid' => 3,
                'section' => 'professional_charges',
                'type_of_price' => 'property_legal_fee',
                'name' => 'facility_agreement',
                'label' => 'Facility Agreement',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'professional_charges',
                'type_of_price' => 'min_pp',
                'name' => 'deed_of_assignment',
                'label' => 'Deed of Assignment(by way of security)',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => 10,
                'min_price' => 300,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'professional_charges',
                'type_of_price' => 'min_pp',
                'name' => 'power_of_attorney',
                'label' => 'Power of Attorney',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => 10,
                'min_price' => 300,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'statutory_declaration',
                'label' => 'Statutory Declaration of Own Occupation & Non Bankruptcy',
                'price' => 200.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'affirmation_sd_fee',
                'label' => 'Affirmation Fee for Statutory Declaration',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'travelling_despatch',
                'label' => 'Travelling & Despatch',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'courier_postage',
                'label' => 'Courier & Postage',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'printing_stationery',
                'label' => 'Printing and Stationery',
                'price' => 150.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'misc',
                'label' => 'Miscellaneous',
                'price' => 100.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'purchase_document_fees',
                'label' => 'Purchase Document Fees',
                'price' => 350.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'property_legal_fee',
                'name' => 'stamp_duty_facility_agreement',
                'label' => 'Stamp Duty on Facility Agreement(FA)',
                'price' => null,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_dfa',
                'label' => 'Stamp Duty on Duplicate FA - 2 copies',
                'price' => 20.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_letter_offer',
                'label' => 'Stamp Duty on Letter of Offer',
                'price' => 30.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_power_of_attorney',
                'label' => 'Stamp Duty on Power of Attorney',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_deed_of_assignment',
                'label' => 'Stamp Duty on Deed of Assignment',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_statutory_declaration',
                'label' => 'Stamp Duty on Statutory Declaration',
                'price' => 20.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'land_search',
                'label' => 'Land Search / Officeal Land Search',
                'price' => 240.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sup_letter_offer',
                'label' => 'Supplementary Letter of Offer',
                'price' => 0.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'filling_fee_power_of_attorney',
                'label' => 'Filling Fee for Power of Attorney',
                'price' => 120.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'property_legal_fee',
                'name' => 'other_fees',
                'label' => 'Bankruptcy / Winding-up Search',
                'price' => null,
                'subsequent_price' => 30,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 3,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'admin_fee_developer',
                'label' => 'Administrative Fee for Developer',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        $cost_assist_vendor_items = [
            [
                'cid' => 4,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'sale_purchase_fees',
                'label' => 'Sale and Purchase Agreement',
                'price' => 500.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'professional_charges',
                'type_of_price' => 'fix_price',
                'name' => 'cost_of_discharge_of_charge',
                'label' => 'Cost of Discharge of Charge',
                'price' => 500.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'affirmation_sd_fee',
                'label' => 'Affirmation Fee for Statutory Declaration',
                'price' => 40.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'travelling_despatch',
                'label' => 'Travelling & Despatch',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'courier_postage',
                'label' => 'Courier & Postage',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'printing_stationery',
                'label' => 'Printing and Stationery',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'reimbursements',
                'type_of_price' => 'fix_price',
                'name' => 'misc',
                'label' => 'Miscellaneous',
                'price' => 50.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'disbursements',
                'type_of_price' => 'pax',
                'name' => 'ckht_1a',
                'label' => 'CKHT 1A',
                'price' => 400,
                'subsequent_price' => 200,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'disbursements',
                'type_of_price' => 'pax',
                'name' => 'ckht_3',
                'label' => 'CKHT 3',
                'price' => 100,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'disbursements',
                'type_of_price' => 'pax',
                'name' => 'bankruptcy_search',
                'label' => 'Bankruptcy Search',
                'price' => null,
                'subsequent_price' => 30,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'reg_16N',
                'label' => 'Registration of 16N',
                'price' => 90.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'cid' => 4,
                'section' => 'disbursements',
                'type_of_price' => 'fix_price',
                'name' => 'sd_statutory_declaration',
                'label' => 'Stamp Duty of Statutory Declaration',
                'price' => 10.00,
                'subsequent_price' => null,
                'percentage' => null,
                'min_price' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        foreach ($spa_items as $i => $value) {
            $spa_items[$i]["pos"] = $i + 1;
        }
        foreach ($loan_items as $i => $value) {
            $loan_items[$i]["pos"] = $i + 1;
        }
        foreach ($master_loan_items as $i => $value) {
            $master_loan_items[$i]["pos"] = $i + 1;
        }
        foreach ($cost_assist_vendor_items as $i => $value) {
            $cost_assist_vendor_items[$i]["pos"] = $i + 1;
        }

        CalculatorItem::insert(array_merge($spa_items, $loan_items, $master_loan_items, $cost_assist_vendor_items));
    }
}
